name: CD

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      env:
        VERSION:  ${{ github.event.release.tag_name }}
      run : |
        echo TEST $VERSION
